### ISSUE TITLE
"Film Grain" and "Lense Flare" compilation issues 

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory#1416]
- **compilation will fail, if you activate "Film Grain" and then desactivate it.**
"Film Grain" it will work if you activate it just one time and never change the setting.

You will get the following errors :
```
	ERROR: C:\test\build_test\compiled\Shaders\compositor_pass.frag.glsl:274: 'compoGrainStrength' : undeclared identifier
	ERROR: C:\test\build_test\compiled\Shaders\compositor_pass.frag.glsl:274: '' : missing #endif
	ERROR: C:\test\build_test\compiled\Shaders\compositor_pass.frag.glsl:274: '' : compilation terminated
```
Are there any way I can deactivate the "Film Grain" and compile my project?

- **compilation will fail, if you activate "Lense Flare".**
- **compilation will fail, if you activate "Lense Flare" and then desactivate it.**
"Lense Flare" do not work
```
	ERROR: C:\test\build_test\compiled\Shaders\compositor_pass.frag.glsl:260: 'gbufferD' : undeclared identifier
	ERROR: C:\test\build_test\compiled\Shaders\compositor_pass.frag.glsl:260: '' : missing #endif
	ERROR: C:\test\build_test\compiled\Shaders\compositor_pass.frag.glsl:260: '' : compilation terminated
```

**Expected behavior : be able the change the settings at will and be able to compile the project.**

Windows 10
Intel 630

![2019-09-28 22_57_23-Blender  C__Users_devWin10_Desktop_seed2_seed_123irose mobile_test blend](https://user-images.githubusercontent.com/53947594/65822549-906a8980-e246-11e9-9905-e7ae44e06a45.jpg)

**Comment by BlackGoku36** [comment]
@onelsonic  film grain work fine for me, are you using latest git armory?
for, lens flare, https://github.com/armory3d/armory/pull/1417 should fix it

**Comment by onelsonic** [comment]
if I create a new project and activate the "Film grain" : it works
But if I then deactivate the "Film grain", the project will not compile any more.

**Comment by luboslenco** [comment]
Hm, if I activate `Film grain` -> run -> deactivate `Film grain` -> run again then it still appears to work here. Does this happen for empty project as well? Maybe some other option triggers it?

**Comment by onelsonic** [comment]
- starting from an empty project or simple cube scene works fine.
- using an existing project triggers the error, I will try to isolate what is causing the issue.

**Comment by luboslenco** [comment]
Please reopen with sample project if issue still persists.
