### ISSUE TITLE
armorySDK1911 bullet broken on HashLink

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory#1461]
Hi there, 
not sure what is causing this but the compilation is now broken.
You will get the following errors coming from haxebullet : bullet.idl see the blender console errors below :

```
/armorySDK1911/lib/haxebullet/Sources/bullet/bullet.idl:805: lines 805-806 : Type name should start with an uppercase letter: "tNodeArray"

/armorySDK1911/lib/haxebullet/Sources/bullet/bullet.idl:805: lines 805-806 : Type name should start with an uppercase letter: "tNodeArray_Impl_"

/armorySDK1911/lib/haxebullet/Sources/bullet/bullet.idl:819: lines 819-820 : Type name should start with an uppercase letter: "tMaterialArray"

c:/armorySDK1911/lib/haxebullet/Sources/bullet/bullet.idl:819: lines 819-820 : Type name should start with an uppercase letter: "tMaterialArray_Impl_"

Haxe compiler error.
```

**Comment by luboslenco** [comment]
Maybe related with update to Haxe 4 https://github.com/Kode/Kha/commit/dbe02ed4aacdfdef710fdca03a9a7890076d760e.

**Comment by onelsonic** [comment]
@luboslenco a quick question, the current Krom version in ArmorySDK1911 has been compiled using Haxe 3.4.7 and not Haxe 4 ? Am I right?

**Comment by luboslenco** [comment]
Hi, Krom is not compiled using Haxe. Krom = [Kinc](https://github.com/Kode/Kinc) + JS engine. Afterwards Haxe compiles into JS which Krom runs.

**Comment by onelsonic** [comment]
ok I see. thank you for the feedback.

**Comment by luboslenco** [comment]
Should be resolved now in ArmorySDK-2019-12. 🔨

**Comment by onelsonic** [comment]
Hi there, 
I just upgraded my setup to blender 2.81 and tested the last SDK 2019.12
and still have issues with bullet and the HaskLink targets, 

below is what you get when targeting Android :

-------------------
Armory v2019.12 ($Id: 94dc8b99633e01e2432e7b7818ba7c0fe7a461a9 $)
OS: win, Target: html5, GAPI: webgl, Blender: 2.81 (sub 16)

----
ArmorySDK\armory\Sources/armory/trait/physics/bullet/RigidBody.hx:257: characters 100-122 : bullet.CollisionObject has no field CF_NO_CONTACT_RESPONSE
ArmorySDK\armory\Sources/armory/trait/physics/bullet/RigidBody.hx:259: characters 88-107 : bullet.CollisionObject has no field CF_KINEMATIC_OBJECT
ArmorySDK\armory\Sources/armory/trait/physics/bullet/RigidBody.hx:260: characters 89-105 : bullet.CollisionObject has no field CF_STATIC_OBJECT
ArmorySDK\armory\Sources/armory/trait/physics/bullet/RigidBody.hx:262: characters 115-131 : bullet.CollisionObject has no field CF_STATIC_OBJECT
ArmorySDK\armory\Sources/armory/trait/physics/bullet/RigidBody.hx:461: characters 8-25 : bullet.RigidBody has no field setWorldTransform

------
Haxe compiler error.
Finished in 12.582347568923445
Build failed, check console

**Comment by Pataxu** [comment]
Same here, when I use physics (A rigidbody) and I try to export, I get this:

C:\Users\User\Documents\ArmorySDK\armory\Sources/armory/trait/physics/bullet/RigidBody.hx:461: characters 8-25 : bullet.RigidBody has no field setWorldTransform
C:\Users\User\Documents\ArmorySDK\armory\Sources/armory/trait/physics/bullet/RigidBody.hx:257: characters 100-122 : bullet.CollisionObject has no field CF_NO_CONTACT_RESPONSE
C:\Users\User\Documents\ArmorySDK\armory\Sources/armory/trait/physics/bullet/RigidBody.hx:259: characters 88-107 : bullet.CollisionObject has no field CF_KINEMATIC_OBJECT
C:\Users\User\Documents\ArmorySDK\armory\Sources/armory/trait/physics/bullet/RigidBody.hx:260: characters 89-105 : bullet.CollisionObject has no field CF_STATIC_OBJECT
C:\Users\User\Documents\ArmorySDK\armory\Sources/armory/trait/physics/bullet/RigidBody.hx:262: characters 115-131 : bullet.CollisionObject has no field CF_STATIC_OBJECT

This is what I get when I built with Android and Windows (C), I can build with Windows (Krom) but I end up getting a black screen in game.

**Comment by luboslenco** [comment]
Fix merged, link to https://github.com/armory3d/armory/issues/1504.
