### ISSUE TITLE
'F5' in Blender = GL Error 1282, ERROR: Use of undeclared identifier,Uniform projectionMatrix not found and more....

### ISSUE THREAD

**Issue by Lykdraft** [armory3d/armory#1911]
Latest SDK from single-clone repo today:

These errors are more or less the same with the examples and my own projects. 
They do run but look completely broken, graphics are glitched out... 
Sometimes there is just only a black screen...

_(Before this I couldn't get any new SDK running because of "Couldn't find krom.js, aborting"
This at least is gone now. I still have to use  SDK 2020.9 as this one seem to work without any bigger problems... )_

System: OSX 10.14.6, Blender 2.83

    __________  [Armory] Compiling  __________
    Exporting Scene
    Scene exported in 0.001767873764038086
    Exporting Scene.001
    Warning: No camera found in active scene layers
    Scene exported in 0.016785860061645508
    Finished in 0.8271791934967041
    Warning: 1 warnings occurred during compilation
    deviceBufferSize = 4096

    mSampleRate = 44100

    mFormatFlags = 00000009

    mBytesPerPacket = 8

    mFramesPerPacket = 1

    mChannelsPerFrame = 2

    mBytesPerFrame = 8

    mBitsPerChannel = 32

    GLSL compiler error: ERROR: 0:6: Unknown identifier 'binding' in layout
    ERROR: 0:14: Use of undeclared identifier 'tex'
    ERROR: 0:15: Use of undeclared identifier 'texcolor'
    ERROR: 0:16: Use of undeclared identifier 'texcolor'
    ERROR: 0:16: Use of undeclared identifier '_32'
    ERROR: 0:16: Use of undeclared identifier '_32'
    ERROR: 0:16: Use of undeclared identifier '_32'
    ERROR: 0:16: Use of undeclared identifier 'texcolor'
    ERROR: 0:17: Use of undeclared identifier 'texcolor'

    GLSL linker error: ERROR: One or more attached shaders not successfully compiled

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 392

    Uniform projectionMatrix not found.
    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 410

    GLSL compiler error: ERROR: 0:6: Unknown identifier 'binding' in layout
    ERROR: 0:14: Use of undeclared identifier 'tex'

    GLSL linker error: ERROR: One or more attached shaders not successfully compiled

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 392

    Uniform projectionMatrix not found.
    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 410

    GLSL compiler error: ERROR: 0:6: Unknown identifier 'binding' in layout
    ERROR: 0:14: Use of undeclared identifier 'tex'
    ERROR: 0:15: Use of undeclared identifier 'texcolor'
    ERROR: 0:16: Use of undeclared identifier 'texcolor'
    ERROR: 0:16: Use of undeclared identifier '_32'
    ERROR: 0:16: Use of undeclared identifier '_32'
    ERROR: 0:16: Use of undeclared identifier '_32'
    ERROR: 0:16: Use of undeclared identifier 'texcolor'
    ERROR: 0:17: Use of undeclared identifier 'texcolor'

    GLSL linker error: ERROR: One or more attached shaders not successfully compiled

    GLSL compiler error: ERROR: 0:6: Unknown identifier 'binding' in layout
    ERROR: 0:8: Unknown identifier 'binding' in layout
    ERROR: 0:9: Unknown identifier 'binding' in layout
    ERROR: 0:10: Unknown identifier 'binding' in layout
    ERROR: 0:16: Unknown identifier 'binding' in layout
    ERROR: 0:156: Use of undeclared identifier 'shadowMapPoint'
    ERROR: 0:157: Use of undeclared identifier '_456'
    ERROR: 0:164: Use of undeclared identifier 'gbuffer0'
    ERROR: 0:166: Use of undeclared identifier 'g0'
    ERROR: 0:166: Use of undeclared identifier 'g0'
    ERROR: 0:170: Use of undeclared identifier 'g0'
    ERROR: 0:174: Use of undeclared identifier 'g0'
    ERROR: 0:178: Use of undeclared identifier 'g0'
    ERROR: 0:181: Use of undeclared identifier 'g0'
    ERROR: 0:184: Use of undeclared identifier 'gbuffer1'
    ERROR: 0:185: Use of undeclared identifier 'g1'
    ERROR: 0:186: Use of undeclared identifier 'g1'
    ERROR: 0:187: Use of undeclared identifier 'g1'
    ERROR: 0:188: Use of undeclared identifier 'gbufferD'
    ERROR: 0:189: Use of undeclared identifier 'depth'
    ERROR: 0:190: Use of undeclared identifier 'p'
    ERROR: 0:191: Use of undeclared identifier 'v'
    ERROR: 0:193: Use of undeclared identifier 'albedo'
    ERROR: 0:194: Use of undeclared identifier 'occspec'
    ERROR: 0:196: Use of undeclared identifier 'ssaotex'
    ERROR: 0:197: Use of undeclared identifier '_717'
    ERROR: 0:197: Use of undeclared identifier '_717'
    ERROR: 0:197: Use of undeclared identifier '_717'
    ERROR: 0:201: Use of undeclared identifier 'p'
    ERROR: 0:201: Use of undeclared identifier 'v'
    ERROR: 0:201: Use of undeclared identifier 'dotNV'
    ERROR: 0:201: Use of undeclared identifier 'albedo'
    ERROR: 0:201: Use of undeclared identifier 'roughness'
    ERROR: 0:201: Use of undeclared identifier 'occspec'
    ERROR: 0:201: Use of undeclared identifier 'f0'
    ERROR: 0:202: Use of undeclared identifier '_742'
    ERROR: 0:202: Use of undeclared identifier '_742'
    ERROR: 0:202: Use of undeclared identifier '_742'

    GLSL linker error: ERROR: One or more attached shaders not successfully compiled

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 392

    Uniform invVP not found.
    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 392

    Uniform eye not found.
    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 392

    Uniform envmapStrength not found.
    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 392

    Uniform shirr not found.
    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 392

    Uniform cameraProj not found.
    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 392

    Uniform eyeLook not found.
    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 392

    Uniform lightProj not found.
    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 392

    Uniform pointPos not found.
    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 392

    Uniform pointCol not found.
    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 392

    Uniform pointBias not found.
    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 410

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 410

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 410

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 410

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 410

    GLSL compiler error: ERROR: 0:6: Unknown identifier 'binding' in layout
    ERROR: 0:7: Unknown identifier 'binding' in layout
    ERROR: 0:44: Use of undeclared identifier 'gbufferD'
    ERROR: 0:45: Use of undeclared identifier 'depth'
    ERROR: 0:50: Use of undeclared identifier 'gbuffer0'
    ERROR: 0:52: Use of undeclared identifier 'enc'
    ERROR: 0:52: Use of undeclared identifier 'enc'
    ERROR: 0:56: Use of undeclared identifier 'enc'
    ERROR: 0:60: Use of undeclared identifier 'enc'
    ERROR: 0:65: Use of undeclared identifier 'depth'
    ERROR: 0:66: Use of undeclared identifier 'currentPos'
    ERROR: 0:67: Use of undeclared identifier 'currentDistance'
    ERROR: 0:68: Use of undeclared identifier 'currentDistance'
    ERROR: 0:75: Use of undeclared identifier 'currentDistanceA'
    ERROR: 0:76: Use of undeclared identifier 'depth'
    ERROR: 0:76: Use of undeclared identifier 'gbufferD'
    ERROR: 0:76: Use of undeclared identifier 'k'
    ERROR: 0:77: Use of undeclared identifier 'depth'
    ERROR: 0:77: Use of undeclared identifier 'k'
    ERROR: 0:77: Use of undeclared identifier 'currentPos'
    ERROR: 0:78: Use of undeclared identifier 'pos'
    ERROR: 0:78: Use of undeclared identifier 'currentDistanceB'
    ERROR: 0:78: Use of undeclared identifier 'pos'
    ERROR: 0:78: Use of undeclared identifier 'pos'

    GLSL linker error: ERROR: One or more attached shaders not successfully compiled

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 392

    Uniform invVP not found.
    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 392

    Uniform eye not found.
    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 392

    Uniform cameraProj not found.
    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 392

    Uniform eyeLook not found.
    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 392

    Uniform screenSize not found.
    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 392

    Uniform PPComp11 not found.
    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 392

    Uniform PPComp12 not found.
    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 410

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 410

    GLSL compiler error: ERROR: 0:8: Unknown identifier 'binding' in layout
    ERROR: 0:9: Unknown identifier 'binding' in layout
    ERROR: 0:40: Use of undeclared identifier 'gbuffer0'
    ERROR: 0:41: Use of undeclared identifier 'tex'
    ERROR: 0:46: Use of undeclared identifier 'gbuffer0'
    ERROR: 0:47: Use of undeclared identifier 'nor2'
    ERROR: 0:47: Use of undeclared identifier 'nor'
    ERROR: 0:48: Use of undeclared identifier 'tex'
    ERROR: 0:49: Use of undeclared identifier 'influenceFactor'
    ERROR: 0:50: Use of undeclared identifier 'col'
    ERROR: 0:50: Use of undeclared identifier 'w'
    ERROR: 0:51: Use of undeclared identifier 'w'
    ERROR: 0:52: Use of undeclared identifier 'nor2'
    ERROR: 0:52: Use of undeclared identifier 'gbuffer0'
    ERROR: 0:53: Use of undeclared identifier 'influenceFactor'
    ERROR: 0:53: Use of undeclared identifier 'nor2'
    ERROR: 0:53: Use of undeclared identifier 'nor'
    ERROR: 0:54: Use of undeclared identifier 'col'
    ERROR: 0:54: Use of undeclared identifier 'tex'
    ERROR: 0:55: Use of undeclared identifier 'w'
    ERROR: 0:55: Use of undeclared identifier 'influenceFactor'
    ERROR: 0:56: Use of undeclared identifier 'col'
    ERROR: 0:56: Use of undeclared identifier 'w'
    ERROR: 0:57: Use of undeclared identifier 'w'

    GLSL linker error: ERROR: One or more attached shaders not successfully compiled

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 392

    Uniform dirInv not found.
    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 410

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 410

    GLSL compiler error: ERROR: 0:8: Unknown identifier 'binding' in layout
    ERROR: 0:9: Unknown identifier 'binding' in layout
    ERROR: 0:40: Use of undeclared identifier 'gbuffer0'
    ERROR: 0:41: Use of undeclared identifier 'tex'
    ERROR: 0:46: Use of undeclared identifier 'gbuffer0'
    ERROR: 0:47: Use of undeclared identifier 'nor2'
    ERROR: 0:47: Use of undeclared identifier 'nor'
    ERROR: 0:48: Use of undeclared identifier 'tex'
    ERROR: 0:49: Use of undeclared identifier 'influenceFactor'
    ERROR: 0:50: Use of undeclared identifier 'col'
    ERROR: 0:50: Use of undeclared identifier 'w'
    ERROR: 0:51: Use of undeclared identifier 'w'
    ERROR: 0:52: Use of undeclared identifier 'nor2'
    ERROR: 0:52: Use of undeclared identifier 'gbuffer0'
    ERROR: 0:53: Use of undeclared identifier 'influenceFactor'
    ERROR: 0:53: Use of undeclared identifier 'nor2'
    ERROR: 0:53: Use of undeclared identifier 'nor'
    ERROR: 0:54: Use of undeclared identifier 'col'
    ERROR: 0:54: Use of undeclared identifier 'tex'
    ERROR: 0:55: Use of undeclared identifier 'w'
    ERROR: 0:55: Use of undeclared identifier 'influenceFactor'
    ERROR: 0:56: Use of undeclared identifier 'col'
    ERROR: 0:56: Use of undeclared identifier 'w'
    ERROR: 0:57: Use of undeclared identifier 'w'

    GLSL linker error: ERROR: One or more attached shaders not successfully compiled

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 392

    Uniform dirInv not found.
    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 410

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 410

    GLSL compiler error: ERROR: 0:8: Unknown identifier 'binding' in layout
    ERROR: 0:9: Unknown identifier 'binding' in layout
    ERROR: 0:40: Use of undeclared identifier 'gbuffer0'
    ERROR: 0:41: Use of undeclared identifier 'tex'
    ERROR: 0:46: Use of undeclared identifier 'gbuffer0'
    ERROR: 0:47: Use of undeclared identifier 'nor2'
    ERROR: 0:47: Use of undeclared identifier 'nor'
    ERROR: 0:48: Use of undeclared identifier 'tex'
    ERROR: 0:49: Use of undeclared identifier 'influenceFactor'
    ERROR: 0:50: Use of undeclared identifier 'col'
    ERROR: 0:50: Use of undeclared identifier 'w'
    ERROR: 0:51: Use of undeclared identifier 'w'
    ERROR: 0:52: Use of undeclared identifier 'nor2'
    ERROR: 0:52: Use of undeclared identifier 'gbuffer0'
    ERROR: 0:53: Use of undeclared identifier 'influenceFactor'
    ERROR: 0:53: Use of undeclared identifier 'nor2'
    ERROR: 0:53: Use of undeclared identifier 'nor'
    ERROR: 0:54: Use of undeclared identifier 'col'
    ERROR: 0:54: Use of undeclared identifier 'tex'
    ERROR: 0:55: Use of undeclared identifier 'w'
    ERROR: 0:55: Use of undeclared identifier 'influenceFactor'
    ERROR: 0:56: Use of undeclared identifier 'col'
    ERROR: 0:56: Use of undeclared identifier 'w'
    ERROR: 0:57: Use of undeclared identifier 'w'

    GLSL linker error: ERROR: One or more attached shaders not successfully compiled

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 392

    Uniform dirInv not found.
    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 410

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 410

    GLSL compiler error: ERROR: 0:8: Unknown identifier 'binding' in layout
    ERROR: 0:9: Unknown identifier 'binding' in layout
    ERROR: 0:40: Use of undeclared identifier 'gbuffer0'
    ERROR: 0:41: Use of undeclared identifier 'tex'
    ERROR: 0:46: Use of undeclared identifier 'gbuffer0'
    ERROR: 0:47: Use of undeclared identifier 'nor2'
    ERROR: 0:47: Use of undeclared identifier 'nor'
    ERROR: 0:48: Use of undeclared identifier 'tex'
    ERROR: 0:49: Use of undeclared identifier 'influenceFactor'
    ERROR: 0:50: Use of undeclared identifier 'col'
    ERROR: 0:50: Use of undeclared identifier 'w'
    ERROR: 0:51: Use of undeclared identifier 'w'
    ERROR: 0:52: Use of undeclared identifier 'nor2'
    ERROR: 0:52: Use of undeclared identifier 'gbuffer0'
    ERROR: 0:53: Use of undeclared identifier 'influenceFactor'
    ERROR: 0:53: Use of undeclared identifier 'nor2'
    ERROR: 0:53: Use of undeclared identifier 'nor'
    ERROR: 0:54: Use of undeclared identifier 'col'
    ERROR: 0:54: Use of undeclared identifier 'tex'
    ERROR: 0:55: Use of undeclared identifier 'w'
    ERROR: 0:55: Use of undeclared identifier 'influenceFactor'
    ERROR: 0:56: Use of undeclared identifier 'col'
    ERROR: 0:56: Use of undeclared identifier 'w'
    ERROR: 0:57: Use of undeclared identifier 'w'

    GLSL linker error: ERROR: One or more attached shaders not successfully compiled

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 392

    Uniform dirInv not found.
    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 410

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 410

    GLSL compiler error: ERROR: 0:6: Unknown identifier 'binding' in layout
    ERROR: 0:20: Use of undeclared identifier 'tex'

    GLSL linker error: ERROR: One or more attached shaders not successfully compiled

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 410

    GLSL compiler error: ERROR: 0:6: Unknown identifier 'binding' in layout
    ERROR: 0:17: Use of undeclared identifier 'colorTex'
    ERROR: 0:18: Use of undeclared identifier 'colorTex'
    ERROR: 0:19: Use of undeclared identifier 'C'
    ERROR: 0:19: Use of undeclared identifier 'Cleft'
    ERROR: 0:21: Use of undeclared identifier 't'
    ERROR: 0:21: Use of undeclared identifier 't'
    ERROR: 0:21: Use of undeclared identifier 't'
    ERROR: 0:22: Use of undeclared identifier 'colorTex'
    ERROR: 0:23: Use of undeclared identifier 't'
    ERROR: 0:23: Use of undeclared identifier 'C'
    ERROR: 0:23: Use of undeclared identifier 'Ctop'
    ERROR: 0:24: Use of undeclared identifier 't'
    ERROR: 0:24: Use of undeclared identifier 't'
    ERROR: 0:24: Use of undeclared identifier 't'
    ERROR: 0:30: Use of undeclared identifier 'colorTex'
    ERROR: 0:31: Use of undeclared identifier 't'
    ERROR: 0:31: Use of undeclared identifier 'C'
    ERROR: 0:31: Use of undeclared identifier 'Cright'
    ERROR: 0:32: Use of undeclared identifier 't'
    ERROR: 0:32: Use of undeclared identifier 't'
    ERROR: 0:32: Use of undeclared identifier 't'
    ERROR: 0:33: Use of undeclared identifier 'colorTex'
    ERROR: 0:34: Use of undeclared identifier 't'
    ERROR: 0:34: Use of undeclared identifier 'C'
    ERROR: 0:34: Use of undeclared identifier 'Cbottom'
    ERROR: 0:35: Use of undeclared identifier 't'
    ERROR: 0:35: Use of undeclared identifier 't'
    ERROR: 0:35: Use of undeclared identifier 't'
    ERROR: 0:37: Use of undeclared identifier 'colorTex'
    ERROR: 0:38: Use of undeclared identifier 't'
    ERROR: 0:38: Use of undeclared identifier 'C'
    ERROR: 0:38: Use of undeclared identifier 'Cleftleft'
    ERROR: 0:39: Use of undeclared identifier 't'
    ERROR: 0:39: Use of undeclared identifier 't'
    ERROR: 0:39: Use of undeclared identifier 't'
    ERROR: 0:40: Use of undeclared identifier 'colorTex'
    ERROR: 0:41: Use of undeclared identifier 't'
    ERROR: 0:41: Use of undeclared identifier 'C'
    ERROR: 0:41: Use of undeclared identifier 'Ctoptop'
    ERROR: 0:42: Use of undeclared identifier 't'
    ERROR: 0:42: Use of undeclared identifier 't'
    ERROR: 0:42: Use of undeclared identifier 't'

    GLSL linker error: ERROR: One or more attached shaders not successfully compiled

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 392

    Uniform screenSizeInv not found.
    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 410

    GLSL compiler error: ERROR: 0:7: Unknown identifier 'binding' in layout
    ERROR: 0:8: Unknown identifier 'binding' in layout
    ERROR: 0:9: Unknown identifier 'binding' in layout
    ERROR: 0:36: Use of undeclared identifier 'edgesTex'
    ERROR: 0:56: Use of undeclared identifier 'areaTex'
    ERROR: 0:77: Use of undeclared identifier 'edgesTex'
    ERROR: 0:113: Use of undeclared identifier 'edgesTex'
    ERROR: 0:115: Use of undeclared identifier '_374'
    ERROR: 0:115: Use of undeclared identifier '_374'
    ERROR: 0:118: Use of undeclared identifier 'edgesTex'
    ERROR: 0:119: Use of undeclared identifier '_386'
    ERROR: 0:119: Use of undeclared identifier '_386'
    ERROR: 0:145: Use of undeclared identifier 'edgesTex'
    ERROR: 0:164: Use of undeclared identifier 'edgesTex'
    ERROR: 0:167: Use of undeclared identifier 'edgesTex'
    ERROR: 0:170: Use of undeclared identifier 'edgesTex'
    ERROR: 0:171: Use of undeclared identifier '_525'
    ERROR: 0:171: Use of undeclared identifier '_525'
    ERROR: 0:200: Use of undeclared identifier 'searchTex'
    ERROR: 0:231: Use of undeclared identifier 'edgesTex'
    ERROR: 0:274: Use of undeclared identifier 'edgesTex'
    ERROR: 0:294: Use of undeclared identifier 'areaTex'
    ERROR: 0:305: Use of undeclared identifier 'edgesTex'
    ERROR: 0:308: Use of undeclared identifier 'edgesTex'
    ERROR: 0:311: Use of undeclared identifier 'edgesTex'
    ERROR: 0:314: Use of undeclared identifier 'edgesTex'
    ERROR: 0:347: Use of undeclared identifier 'edgesTex'
    ERROR: 0:390: Use of undeclared identifier 'edgesTex'
    ERROR: 0:413: Use of undeclared identifier 'edgesTex'
    ERROR: 0:416: Use of undeclared identifier 'edgesTex'
    ERROR: 0:419: Use of undeclared identifier 'edgesTex'
    ERROR: 0:422: Use of undeclared identifier 'edgesTex'
    ERROR: 0:432: Use of undeclared identifier 'edgesTex'
    ERROR: 0:433: Use of undeclared identifier 'e'
    ERROR: 0:436: Use of undeclared identifier 'e'
    ERROR: 0:438: Use of undeclared identifier 'param_3'
    ERROR: 0:439: Use of undeclared identifier '_1039'
    ERROR: 0:439: Use of undeclared identifier '_1039'
    ERROR: 0:452: Use of undeclared identifier 'edgesTex'
    ERROR: 0:462: Use of undeclared identifier 'edgesTex'
    ERROR: 0:464: Use of undeclared identifier 'e1'
    ERROR: 0:465: Use of undeclared identifier 'e2'
    ERROR: 0:467: Use of undeclared identifier 'param_14'
    ERROR: 0:467: Use of undeclared identifier 'param_15'
    ERROR: 0:468: Use of undeclared identifier '_1124'
    ERROR: 0:468: Use of undeclared identifier '_1124'
    ERROR: 0:478: Use of undeclared identifier 'e'
    ERROR: 0:481: Use of undeclared identifier 'e'
    ERROR: 0:493: Use of undeclared identifier 'edgesTex'
    ERROR: 0:503: Use of undeclared identifier 'edgesTex'
    ERROR: 0:505: Use of undeclared identifier 'e1_1'
    ERROR: 0:506: Use of undeclared identifier 'e2_1'
    ERROR: 0:508: Use of undeclared identifier 'param_29'
    ERROR: 0:508: Use of undeclared identifier 'param_30'
    ERROR: 0:509: Use of undeclared identifier '_1216'
    ERROR: 0:509: Use of undeclared identifier '_1216'

    GLSL linker error: ERROR: One or more attached shaders not successfully compiled

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 392

    Uniform screenSize not found.
    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 392

    Uniform screenSizeInv not found.
    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 410

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 410

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 410

    GLSL compiler error: ERROR: 0:6: Unknown identifier 'binding' in layout
    ERROR: 0:7: Unknown identifier 'binding' in layout
    ERROR: 0:22: Use of undeclared identifier 'blendTex'
    ERROR: 0:23: Use of undeclared identifier 'blendTex'
    ERROR: 0:24: Use of undeclared identifier 'blendTex'
    ERROR: 0:25: Use of undeclared identifier '_54'
    ERROR: 0:25: Use of undeclared identifier '_54'
    ERROR: 0:28: Use of undeclared identifier 'colorTex'
    ERROR: 0:29: Use of undeclared identifier 'color'
    ERROR: 0:50: Use of undeclared identifier 'colorTex'
    ERROR: 0:53: Use of undeclared identifier 'color_1'
    ERROR: 0:53: Use of undeclared identifier 'colorTex'
    ERROR: 0:54: Use of undeclared identifier 'color_1'

    GLSL linker error: ERROR: One or more attached shaders not successfully compiled

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 392

    Uniform screenSizeInv not found.
    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 410

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 410

    arm/MyTrait.hx:19: Suzanne spawned!
    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 209

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 209

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 209

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 209

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 209

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 209

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 209

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 209

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 209

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 209

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 209

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 209

    GL Error 1286 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/OpenGL.cpp 341

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 209

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 209

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 209

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 209

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 209

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 209

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 209

    GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 209

**Comment by luboslenco** [comment]
Should be resolved now in the latest git version (via https://github.com/Kode/krafix/issues/75). Was a macOS only issue.

**Comment by Lykdraft** [comment]
I did a `git submodule update --init --recursive` on the armSDK (single clone repo)
but the error are unfortunately still the same.

**Comment by luboslenco** [comment]
All seems well here - can you verify your local `armsdk/Kha/Kinc/Tools/krafix/krafix-osx` binary matches https://github.com/armory3d/krafix_bin/blob/master/krafix-osx?

**Comment by Lykdraft** [comment]
They didn't match. Don't know why. 
But all is good now, thanks!
