### ISSUE TITLE
V0.1 Error: Array Get - index out of range

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#380]
This exact same .blend did work in build 14, now when I hit F5 the console says `Error: Array Get - index out of range` , the game window refuses to close and a windows command window is flying wildly on the screen.
When pressing F5 again after having closed it with the taskmanager, it doesnt build again and the console says this:
```
Armory v0.1.0 ($Id: 9977a571ccfab9e8e2e587c2a8e02abe843ab21d $)
OS: win, Target: krom, GAPI: opengl
Exporting Scene
Traceback (most recent call last):
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\props_ui.py", line 553, in execute
    make.play_project(False)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\make.py", line 428, in play_project
    build_project(is_play=True, is_render=is_render, is_render_anim=is_render_anim, in_viewport=in_viewport)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\make.py", line 337, in build_project
    export_data(fp, sdk_path, is_play=is_play, is_publish=is_publish, in_viewport=in_viewport)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\make.py", line 120, in export_data
    exporter.execute(bpy.context, asset_path, scene=scene, write_capture_info=state.is_render_anim, play_area=state.play_area)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\exporter.py", line 1992, in execute
    self.export_object(bo, self.scene)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\exporter.py", line 1004, in export_object
    self.export_object(subbobject, scene, o)
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\exporter.py", line 849, in export_object
    o['dimensions'] = [bobject.dimensions[0] / bobject.scale[0], bobject.dimensions[1] / bobject.scale[1], bobject.dimensions[2] / bobject.scale[2]]
ZeroDivisionError: float division by zero

location: <unknown location>:-1

location: <unknown location>:-1
```
The .blend is here: https://drive.google.com/drive/u/0/folders/0B34rrtUThORydTBCeGN2MWZ1c3M

**Comment by luboslenco** [comment]
Windows command window flying  and `float division by zero` when scale is 0 should be fixed now.

`Error: Array Get - index out of range` is caused when trying to access array element which does not exist. For example below - array has 3 elements while `Array Get` node tries to fetch 10th element.

<img width="410" alt="screen shot 2017-12-03 at 11 47 02" src="https://user-images.githubusercontent.com/3685704/33524571-ea526720-d81f-11e7-8927-58e3be50b732.png">

**Comment by Simonrazer** [comment]
Ok thanks! is there a easy way to find out in which Trait this happens, since even when all traits are deactivated on the objects/removed from the objects they were applied to in the scene, this problem occurs.

**Comment by Simonrazer** [comment]
Ähm the problem still exists when all Traits are deleted from the .blend, the project cleaned and Armory restarted. Here the .blend without any Traits:
[divby0.zip](https://github.com/armory3d/armory/files/1524686/divby0.zip)

**Comment by luboslenco** [comment]
There were some unused groups and armory picked that up, should be fixed now.
<img width="449" alt="rbgroup" src="https://user-images.githubusercontent.com/3685704/33543244-9abfbf3e-d8d6-11e7-97ac-e26a4086cc91.png">

We also need better tools to inspect traits, for now I at least added a new operator `Print Traits` which will output a list of present traits into console.
<img width="495" alt="traits" src="https://user-images.githubusercontent.com/3685704/33543285-bd985afc-d8d6-11e7-8798-2db5eb0cfe0b.png">

I also made the error message report an object & trait name now.
`Logic error (object: Cube, trait: NodeTree): Array Get - index out of range`

**Comment by Simonrazer** [comment]
Did not quite understand,but (restoring stable version and updating) copying everything into a new .blend, appending the traits and changing the settings to match the old resolved all issues I had.
