### ISSUE TITLE
HDR doesn't seem to work on osx

### ISSUE THREAD

**Issue by stellanhaglund** [armory3d/armory#585]
I get this every time I set an environment texture
And if I try to add a environment texture to the scene before I have saved it, blender gets stuck at loading and nothing happens.

```
Armory v0.2.0 ($Id: bebbb7fa00e259ed7a026970637a60b0abab7b52 $)
OS: mac, Target: krom, GAPI: opengl
/bin/sh: Armory 5/blender.app//armsdk//lib/armory_tools/cmft/cmft-osx: Permission denied
Traceback (most recent call last):
  File "Armory 5/blender.app//armsdk//armory/blender/arm/props_ui.py", line 603, in execute
    make.play_project(True)
  File "Armory 5/blender.app//armsdk//armory/blender/arm/make.py", line 436, in play_project
    build_project(is_play=True, is_render=is_render, is_render_anim=is_render_anim, in_viewport=in_viewport)
  File "Armory 5/blender.app//armsdk//armory/blender/arm/make.py", line 344, in build_project
    export_data(fp, sdk_path, is_play=is_play, is_publish=is_publish, in_viewport=in_viewport)
  File "Armory 5/blender.app//armsdk//armory/blender/arm/make.py", line 99, in export_data
    make_world.build()
  File "Armory 5/blender.app//armsdk//armory/blender/arm/make_world.py", line 17, in build
    build_node_tree(scene.world)
  File "Armory 5/blender.app//armsdk//armory/blender/arm/make_world.py", line 30, in build_node_tree
    parse_world_output(world, output_node)
  File "Armory 5/blender.app//armsdk//armory/blender/arm/make_world.py", line 64, in parse_world_output
    parse_surface(world, surface_node)
  File "Armory 5/blender.app//armsdk//armory/blender/arm/make_world.py", line 84, in parse_surface
    parse_color(world, color_node)
  File "Armory 5/blender.app//armsdk//armory/blender/arm/make_world.py", line 154, in parse_color
    mip_count = write_probes.write_probes(filepath, disable_hdr, mip_count, arm_radiance=wrd.arm_radiance)
  File "Armory 5/blender.app//armsdk//armory/blender/arm/write_probes.py", line 98, in write_probes
    sh_to_json(output_file_irr)
  File "Armory 5/blender.app//armsdk//armory/blender/arm/write_probes.py", line 233, in sh_to_json
    with open(sh_file + '.c') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'build_testing-hdr/compiled/Assets/envmaps/newport_loft_irradiance.c'

location: <unknown location>:-1
```

**Comment by luboslenco** [comment]
Should be now fixed in latest builds.

**Comment by johnbourne** [comment]
I am still getting a similar error.  I have looked at the write_probes.py file in the Library (on Mac) and find the file is precisely what is shown in the fix -.i.e. used scaled_file rather than Input_file
Here is the traceback I get... Help appreciate - going crazy trying to figure out.  No errors shown on loading from command line on Mac.
<img width="1680" alt="Screen Shot 2019-07-24 at 7 23 38 PM" src="https://user-images.githubusercontent.com/10551699/62230623-d068d980-b387-11e9-8866-7d66b9d02d50.png">
